config/routes.rb
Savethereader::Application.routes.draw do
  get "errors/not_found"

  get "errors/internal_server_error"

  devise_for :users

  match 'sidebar' => 'subscriptions#sidebar', :as => :sidebar, :via => :get
  match 'subscriptions/set_show_read' => 'subscriptions#set_show_read', :as => :set_show_read, :via => :post
  match 'subscriptions/import' => 'subscriptions#import', :as => :import, :via => :get
  match 'subscriptions/upload_import' => 'subscriptions#upload_import', :as => :upload_import, :via => :post
  match 'subscriptions/mark_all_read' => 'subscriptions#mark_all_read', :as => :mark_all_unread, :via => :post
  match 'about' => 'about#index', :as => :about, :via => :get

  resources :subscriptions, :except => [:index, :new, :edit] 
  resources :readentries, :only => [:create, :show]
  resources :subscription_groups, :only => [:create, :show]

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#internal_server_error"

  authenticated :user do
    root :to => "home#s", as: :authenticated_root
  end

  root :to => 'home#index'
  

  
  mount Resque::Server, :at => "/resque"

end

app/models/readentry.rb
class Readentry < ActiveRecord::Base
  attr_accessible :entry_id, :subscription_id
  after_create :invalidate_unread_cache

  validates_presence_of :entry_id, :user_id, :subscription_id
  validates_uniqueness_of :entry_id, :scope => :user_id
  belongs_to :subscription

  def invalidate_unread_cache
    self.subscription.destroy_unread_cache
  end
end

app/controllers/readentries_controller.rb
class ReadentriesController < ApplicationController
  before_filter :authenticate_user!

  # GET /readentries
  # GET /readentries.json
  def index
    @readentries = Readentry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @readentries }
    end
  end

  # GET /readentries/1
  # GET /readentries/1.json
  def show
    @readentry = Readentry.find(params[:id])

    respond_to do |format|
      format.json { render json: @readentry }
    end
  end

  # GET /readentries/new
  # GET /readentries/new.json
  def new
    @readentry = Readentry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @readentry }
    end
  end

  # GET /readentries/1/edit
  def edit
    @readentry = Readentry.find(params[:id])
  end

  # POST /readentries
  # POST /readentries.json
  def create

    @readentry = Readentry.new(params[:readentry])
    @readentry.user_id = current_user.id

    respond_to do |format|
      if @readentry.save
        format.json { render json: @readentry, status: :created, location: @readentry }
      else
        format.json { render json: @readentry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /readentries/1
  # PUT /readentries/1.json
  def update
    @readentry = Readentry.find(params[:id])

    respond_to do |format|
      if @readentry.update_attributes(params[:readentry])
        format.html { redirect_to @readentry, notice: 'Readentry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @readentry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readentries/1
  # DELETE /readentries/1.json
  def destroy
    @readentry = Readentry.find(params[:id])
    @readentry.destroy

    respond_to do |format|
      format.html { redirect_to readentries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/readentries_helper.rb
module ReadentriesHelper
end

app/views/readentries/_form.html.erb
<%= form_for(@readentry) do |f| %>
  <% if @readentry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@readentry.errors.count, "error") %> prohibited this readentry from being saved:</h2>

      <ul>
      <% @readentry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readentries/edit.html.erb
<h1>Editing readentry</h1>

<%= render 'form' %>

<%= link_to 'Show', @readentry %> |
<%= link_to 'Back', readentries_path %>

app/views/readentries/index.html.erb
<h1>Listing readentries</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @readentries.each do |readentry| %>
  <tr>
    <td><%= link_to 'Show', readentry %></td>
    <td><%= link_to 'Edit', edit_readentry_path(readentry) %></td>
    <td><%= link_to 'Destroy', readentry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Readentry', new_readentry_path %>

app/views/readentries/new.html.erb
<h1>New readentry</h1>

<%= render 'form' %>

<%= link_to 'Back', readentries_path %>

app/views/readentries/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_readentry_path(@readentry) %> |
<%= link_to 'Back', readentries_path %>