config/routes.rb
Savethereader::Application.routes.draw do
  get "errors/not_found"

  get "errors/internal_server_error"

  devise_for :users

  match 'sidebar' => 'subscriptions#sidebar', :as => :sidebar, :via => :get
  match 'subscriptions/set_show_read' => 'subscriptions#set_show_read', :as => :set_show_read, :via => :post
  match 'subscriptions/import' => 'subscriptions#import', :as => :import, :via => :get
  match 'subscriptions/upload_import' => 'subscriptions#upload_import', :as => :upload_import, :via => :post
  match 'subscriptions/mark_all_read' => 'subscriptions#mark_all_read', :as => :mark_all_unread, :via => :post
  match 'about' => 'about#index', :as => :about, :via => :get

  resources :subscriptions, :except => [:index, :new, :edit] 
  resources :readentries, :only => [:create, :show]
  resources :subscription_groups, :only => [:create, :show]

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#internal_server_error"

  authenticated :user do
    root :to => "home#s", as: :authenticated_root
  end

  root :to => 'home#index'
  

  
  mount Resque::Server, :at => "/resque"

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :feed_id, :user_id, :group_id
  belongs_to :user
  belongs_to :feed
  belongs_to :subscription_group
  has_many :readentry, :dependent => :destroy
  validates_presence_of :feed_id, :user_id
  validates_uniqueness_of :feed_id, :scope => :user_id
  validate :subscription_limit_reached, :on => :create
  after_touch :destroy_unread_cache
  after_create :destroy_unread_cache

  def self.init(url, group, user_id)
    # first check if feed exists
    feed = Feed.find_by_url_with_feedbag(url)
    feed = Feed.create_and_update url if feed.nil?
    # return if it didn't succeed creating feed
    return Subscription.new if feed.nil? 
    new_sub = Subscription.new :feed_id => feed.id, :user_id => user_id
    new_sub.group_id = new_sub.user.subscription_groups.find_by_name(group).id if !group.nil? && new_sub.user.subscription_groups.exists?(:name => group)
    new_sub
  end

  def unread_count
    return read_unread_number_cache unless read_unread_number_cache.nil?
    r_entries = read_entries.collect {|re| re.entry_id }
    entries = self.feed.entries.where('updated_at > ?', self.updated_at).collect { |entry| entry.id } #watch out for scaling issues
    unread = (entries - r_entries).count
    write_unread_number_cache unread
    unread
  end

  def get_entries(page_num, per_page)
    self.feed.cached_entries(page_num, per_page)
  end

  def self.import(subscriptions, user_id)
    subscriptions.each do |provider, s_file|
      case provider.to_sym
      when :google
        Subscription.import_from_google(s_file, user_id)
      else
        logger.error("no received provider")
      end
    end
  end

  def destroy_unread_cache
    Rails.cache.delete unread_number_cache_key
  end

  private
  def get_unread_entries(page_num, per_page)
    return nil if self.unread_count == 0
    r_entries = read_entries.collect {|re| re.entry_id }
    entries = self.feed.entries.paginate(page: page_num || 1, per_page: per_page || 10, order: 'created_at DESC').to_a
    return entries.keep_if {|e| !r_entries.include? e.id }
  end

  def read_entries
     Readentry.where(:user_id => self.user.id, :subscription_id => self.id)
  end

  def self.import_from_google(file, user_id)
    begin
      Resque.enqueue(GoogleSubscriptionsImporter, user_id, file )
    rescue Exception => e
      logger.error('importing subscriptions ' + e.message)
    end
  end

  # cache methods
  def write_unread_number_cache(num)
    Rails.cache.write unread_number_cache_key, num, :expires_in => 10.minutes
  end

  def read_unread_number_cache
    Rails.cache.read unread_number_cache_key 
  end

  def unread_number_cache_key
    "#{self.id}_unread"
  end

  # validate methods
  def subscription_limit_reached
    errors.add(:user_id, "subscription limit reached") unless Subscription.where(:user_id => self.user_id).count < 250
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!
  require_dependency 'entry'
  #caches_action :show, :cache_path => custom_cache_path.to_proc

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscriptions }
    end
  end

  # GET /subscriptions/1.js
  def show
    @subscription = Subscription.find(params[:id])
    @entries = @subscription.get_entries(params[:page], params[:per_page])
    @subscription_id = @subscription.id
    @user_id = current_user.id
    respond_to do |format|
      format.js
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
    @subscription = Subscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = params[:subscription].nil?? Subscription.init(params[:url], params[:group], current_user.id) : Subscription.new(params[:subscription]) 
    respond_to do |format|
      if @subscription.save
        format.json { render json: @subscription, :include => [:subscription_group, :feed], :methods => :unread_count, status: :created, location: @subscription }
      else
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  # GET /subscriptions/import
  def import

  end

  # POST /subscriptions/upload_import
  def upload_import
    respond_to do |format|
      if Subscription.import(params[:file], current_user.id)
        format.html { redirect_to root_path, notice: 'Your subscriptions are being imported. They will start appearing on your sidebar shortly.' }
        format.json { head :no_content }
      else
        format.html { render action: "import", error: 'Unable to process import.' }
        format.json { render json: { message: "Unable to process import." }, status: :unprocessable_entity }
      end
    end
  end

  # POST /subscriptions/set_show_read.json
  def set_show_read
    show_read_toggle(to_boolean(params[:state]))

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  # GET /sidebar.js
  def sidebar
    @subs_groups = current_user.cached_subscription_groups
    @subs_ungroup = current_user.cached_ungrouped_subscriptions
    respond_to do |format|
      format.js
    end
  end

  # POST /subscriptions/mark_all_read.json
  def mark_all_read
    subscription = Subscription.find(params[:id])

    subscription.touch unless subscription.nil?

    respond_to do |format|
      format.json { head :no_content }
    end

  end

  def custom_cache_path
    "#{params[:id]}-#{params[:page]}-#{params[:controller]}-#{params[:action]}"
  end

  private
  def show_read
    session[:show_read] || false
  end

  def show_read_toggle(state)
    session[:show_read] = state
  end

  def to_boolean(str)
      str == 'true'
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def reached_page_limit(page)
    page.to_i > 50
  end

end

app/views/subscriptions/_feed.html.erb
<% @entries.each do |entry| %>
  <section class="entry <%= entry.is_read(@user_id)? 'read' : 'unread' %>" id="<%= entry.id %>">
  <h3><a href="<%= h(entry.url) %>" class="title-link" target="_blank"><%= entry.title.html_safe %></a></h3>
  <div class="entry-content">
    <div class="tabbable" style="margin-bottom: 18px;">
      <%= Sanitize.clean(entry.content.nil?? entry.summary : entry.content, Sanitize::Config::RELAXED).html_safe %>
      <div class="row pull-right"><%= Time.parse(h(entry.published)).strftime("%FT%R") unless entry.published.nil? %></div>
    </div> <!-- /tabbable -->
  </div>
</section>
<% end unless @entries.nil? %>

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/import.html.erb
<h2>Import your subscriptions</h2>

<%= form_tag(url_for(:controller => :subscriptions, :action => :upload_import), :multipart => true, :method => :post) do %>
  <div>Select your exported subscriptions OPML file.<br />
  <%= file_field_tag 'file[google]' %></div><br />
  <div><%= submit_tag "Upload" %></div>
<% end %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= link_to 'Show', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.js.erb
var page_num = parseIntWithEmpty('<%= params[:page] %>') + 1; 
var page_param = 'page=' + page_num;
console.log('values current: ' + getSelectedSubscriptionId() + ' - subs: ' + <%= @subscription_id %>);
var entries_load_url = '<%= subscription_path(id: @subscription_id, format: :js, page: (params[:page] || 1).to_i + 1, per_page: params[:per_page] || 10) %>';
var isCurrentSubscription = getSelectedSubscriptionId() == <%= @subscription_id %>;
function processEntries() {

  $('a.hook').attr('href', entries_load_url); // set next page url

<% if !@entries.nil? && !@entries.empty? %>

   $(".entry.read").removeClass("read");

   var feed_html = '<%= escape_javascript(render(partial: 'feed', object: @entries)) %>';

   // see if first or else page
   <% if params[:page].to_i == 0 %>
      $('div.feed-view').html(feed_html);
      window.scrollTo(0, 0);
    <% else %>
      $('div.feed-view').append(feed_html);
   <% end %>

   $(".feed-view a").attr("target", "_blank");
   $('.loader').hide();
   
   if ($(".entry.unread").length < 15) {
     <% if reached_page_limit(params[:page]) %>
        showLoadOneMore();
     <% else %>
       $.getScript($('a.hook').attr('href'));
       $('.loader').show();
     <% end %>
   }
   else
    $('.loader').show(); 
   
   // scroll logic 
   bindInviewEntries();
   
   if (!showRead) {
    $(".entry.read").remove();
   }
   else {
     $(".entry.read").fadeTo(0, 0.5);
   }
  <% else %>
     
     $('.loader').hide();

     if ($("#no-entries-banner").length == 0) {
        $("#overview").append("<div id='no-entries-banner' class='hero-unit'><h3>...and that's all there is for now!</h3></div>");
        $('a.hook').attr('href', '');
     }

<% end %>
}

if (isCurrentSubscription)
  processEntries();

showRead = <%= show_read %>;
showRead ?  $(".btn-show-unread").addClass("active") :  $(".btn-show-unread").removeClass("active");
$(".btn-show-unread").html(showRead? showUnreadText : showReadText);

app/views/subscriptions/sidebar.js.erb
var sidebar_html = '<%= escape_javascript(render(partial: 'layouts/sidebar')) %>';
$('#subscription-sidebar').html(sidebar_html);
bindSubscriptionNavigation();