config/routes.rb
Savethereader::Application.routes.draw do
  get "errors/not_found"

  get "errors/internal_server_error"

  devise_for :users

  match 'sidebar' => 'subscriptions#sidebar', :as => :sidebar, :via => :get
  match 'subscriptions/set_show_read' => 'subscriptions#set_show_read', :as => :set_show_read, :via => :post
  match 'subscriptions/import' => 'subscriptions#import', :as => :import, :via => :get
  match 'subscriptions/upload_import' => 'subscriptions#upload_import', :as => :upload_import, :via => :post
  match 'subscriptions/mark_all_read' => 'subscriptions#mark_all_read', :as => :mark_all_unread, :via => :post
  match 'about' => 'about#index', :as => :about, :via => :get

  resources :subscriptions, :except => [:index, :new, :edit] 
  resources :readentries, :only => [:create, :show]
  resources :subscription_groups, :only => [:create, :show]

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#internal_server_error"

  authenticated :user do
    root :to => "home#s", as: :authenticated_root
  end

  root :to => 'home#index'
  

  
  mount Resque::Server, :at => "/resque"

end

app/models/subscription_group.rb
class SubscriptionGroup < ActiveRecord::Base
  attr_accessible :name # :user_id,  :color
  has_many :subscriptions , :foreign_key => :group_id
  belongs_to :user
  after_create :invalidate_user_subs_groups_cache
  validates :name, :presence => true, :length => { :in => 3..20 }
  validates :user_id, :presence => true
  validates_uniqueness_of :name, :scope => :user_id

  def invalidate_user_subs_groups_cache
    self.user.invalidate_subs_groups_cache
  end

end

app/controllers/subscription_groups_controller.rb
class SubscriptionGroupsController < ApplicationController
  before_filter :authenticate_user!

  # GET /subscription_groups
  # GET /subscription_groups.json
  def index
    @subscription_groups = SubscriptionGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscription_groups }
    end
  end

  # GET /subscription_groups/1
  # GET /subscription_groups/1.json
  def show
    @subscription_group = SubscriptionGroup.find(params[:id])

    respond_to do |format|
      format.json { render json: @subscription_group }
    end
  end

  # GET /subscription_groups/new
  # GET /subscription_groups/new.json
  def new
    @subscription_group = SubscriptionGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription_group }
    end
  end

  # GET /subscription_groups/1/edit
  def edit
    @subscription_group = SubscriptionGroup.find(params[:id])
  end

  # POST /subscription_groups
  # POST /subscription_groups.json
  def create
    @subscription_group = SubscriptionGroup.new(params[:subscription_group])
    @subscription_group.user_id = current_user.id
    respond_to do |format|
      if @subscription_group.save
        format.json { render json: @subscription_group, status: :created, location: @subscription_group }
      else
        format.json { render json: @subscription_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscription_groups/1
  # PUT /subscription_groups/1.json
  def update
    @subscription_group = SubscriptionGroup.find(params[:id])

    respond_to do |format|
      if @subscription_group.update_attributes(params[:subscription_group])
        format.html { redirect_to @subscription_group, notice: 'Subscription group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscription_groups/1
  # DELETE /subscription_groups/1.json
  def destroy
    @subscription_group = SubscriptionGroup.find(params[:id])
    @subscription_group.destroy

    respond_to do |format|
      format.html { redirect_to subscription_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subscription_groups_helper.rb
module SubscriptionGroupsHelper
end

app/views/subscription_groups/_form.html.erb
<%= form_for(@subscription_group) do |f| %>
  <% if @subscription_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription_group.errors.count, "error") %> prohibited this subscription_group from being saved:</h2>

      <ul>
      <% @subscription_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscription_groups/edit.html.erb
<h1>Editing subscription_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription_group %> |
<%= link_to 'Back', subscription_groups_path %>

app/views/subscription_groups/index.html.erb
<h1>Listing subscription_groups</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscription_groups.each do |subscription_group| %>
  <tr>
    <td><%= link_to 'Show', subscription_group %></td>
    <td><%= link_to 'Edit', edit_subscription_group_path(subscription_group) %></td>
    <td><%= link_to 'Destroy', subscription_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription group', new_subscription_group_path %>

app/views/subscription_groups/new.html.erb
<h1>New subscription_group</h1>

<%= render 'form' %>

<%= link_to 'Back', subscription_groups_path %>

app/views/subscription_groups/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_subscription_group_path(@subscription_group) %> |
<%= link_to 'Back', subscription_groups_path %>